# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  docker:
    - image: ruedap/node-xcb-noto
  working_directory: ~/cli

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{ checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run: npm install
      - run: ./bin/run --version
      - run: ./bin/run --help
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{ checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules
      - run: npm run ci:test

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{ checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run: npm install
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{ checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules
      - run: npm run deploy-storybook

workflows:
  version: 2
  "abccss":
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
